spring:
  jpa:
    hibernate.ddl-auto: update
    properties:
        default_schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
